apiVersion: stork.libopenstorage.org/v1alpha1
kind: Rule
metadata:
  name: app-freeze
  namespace: px-snapshots
rules:
- podSelector:
    app: px-writer
  actions:
  - type: command
    value: ["sh", "-c", "sync"]
---
apiVersion: stork.libopenstorage.org/v1alpha1
kind: Rule
metadata:
  name: app-thaw
  namespace: px-snapshots
rules:
- podSelector:
    app: px-writer
  actions:
  - type: command
    value: ["sh", "-c", "echo thaw"]

---
apiVersion: stork.libopenstorage.org/v1alpha1
kind: Rule
metadata:
  name: cassandra-freeze
  namespace: px-snapshots
rules:
- podSelector:
    app: cassandra
  actions:
  - type: command
    value: ["sh", "-c", "nodetool flush || true"]

---
apiVersion: stork.libopenstorage.org/v1alpha1
kind: Rule
metadata:
  name: cassandra-thaw
  namespace: px-snapshots
rules:
- podSelector:
    app: cassandra
  actions:
  - type: command
    value: ["sh", "-c", "echo thaw"]

