apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  namespace: px-snapshots
spec:
  serviceName: cassandra
  replicas: 3
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: cassandra:3.11
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        env:
        - name: CASSANDRA_SEEDS
          value: cassandra-0.cassandra.px-snapshots.svc.cluster.local
        - name: MAX_HEAP_SIZE
          value: 512M
        - name: HEAP_NEWSIZE
          value: 100M
        - name: CASSANDRA_CLUSTER_NAME
          value: "Test Cluster"
        - name: CASSANDRA_DC
          value: "DC1"
        - name: CASSANDRA_RACK
          value: "RACK1"
        - name: CASSANDRA_ENDPOINT_SNITCH
          value: GossipingPropertyFileSnitch
        volumeMounts:
        - name: data
          mountPath: /var/lib/cassandra
        - name: commitlog
          mountPath: /var/lib/cassandra-commitlog
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: cassandra
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: px-sc
      resources:
        requests:
          storage: 5Gi
  - metadata:
      name: commitlog
      labels:
        app: cassandra
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: px-sc
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: px-snapshots
  labels:
    app: cassandra
spec:
  clusterIP: None
  ports:
  - name: intra-node
    port: 7000
  - name: tls-intra-node
    port: 7001
  - name: jmx
    port: 7199
  - name: cql
    port: 9042
  selector:
    app: cassandra

