apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: px-data-fast
  namespace: px-snapshots
  labels:
    app: px-writer
spec:
  storageClassName: px-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

