---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fio-repl3
provisioner: pxd.portworx.com
parameters:
  repl: "3"
  io_profile: "db_remote"
allowVolumeExpansion: true
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fio-repl3-encrypted
provisioner: pxd.portworx.com
parameters:
  repl: "3"
  io_profile: "db_remote"
  secure: "true"
allowVolumeExpansion: true