kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-data
  namespace: px-volume-expansion
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: px-postgres-sc