apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: mysql-snap-local
  namespace: px-snapshots
spec:
  volumeSnapshotClassName: px-mysql-snapclass-local
  source:
    persistentVolumeClaimName: mysql-px

