apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: px-mysql-snapclass-local
driver: pxd.portworx.com
deletionPolicy: Delete
parameters:
  portworx/snapshot-type: local

