apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-px
  namespace: px-snapshots
  labels:
    app: mysql
spec:
  storageClassName: px-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

