apiVersion: v1
kind: Namespace
metadata:
  name: px-bench
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: px-bench
  namespace: px-bench

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: px-bench-results
  namespace: px-bench
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  # storageClassName: px-bench-results
  # IMPORTANT: set to a Portworx RWX-capable StorageClass in your cluster

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: repl1-fastpath
provisioner: pxd.portworx.com
parameters:
  repl: "1"
  fastpath: "true"
allowVolumeExpansion: true

--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: fiocfg
  namespace: px-bench
data:
  fiojobs.fio: |-
    [global]
    ioengine=libaio
    name=test
    direct=1
    iodepth=128
    stonewall
    filename=/data/fio.dat
    buffer_compress_percentage=50
    end_fsync=1
    # runtime and size can be overridden via CLI flags from the runner
    ##----Begin 4k tests-------
    [4k-write]
    blocksize=4k
    readwrite=write
    [4k-read]
    blocksize=4k
    readwrite=read
    [4k-rand-write]
    blocksize=4k
    readwrite=randwrite
    [4k-rand-read]
    blocksize=4k
    readwrite=randread
    [4k-mix-rand-50-50]
    blocksize=4k
    readwrite=randrw
    rwmixread=50
    [4k-mix-rand-80-20]
    blocksize=4k
    readwrite=randrw
    rwmixread=80
    [4k-mix-rand-20-80]
    blocksize=4k
    readwrite=randrw
    rwmixread=20
    ##----Begin 16k tests-------
    [16k-write]
    blocksize=16k
    readwrite=write
    [16k-read]
    blocksize=16k
    readwrite=read
    [16k-rand-write]
    blocksize=16k
    readwrite=randwrite
    [16k-rand-read]
    blocksize=16k
    readwrite=randread
    [16k-mix-rand-50-50]
    blocksize=16k
    readwrite=randrw
    rwmixread=50
    [16k-mix-rand-80-20]
    blocksize=16k
    readwrite=randrw
    rwmixread=80
    [16k-mix-rand-20-80]
    blocksize=16k
    readwrite=randrw
    rwmixread=20
    ##----Begin 64k tests-------
    [64k-write]
    blocksize=64k
    readwrite=write
    [64k-read]
    blocksize=64k
    readwrite=read
    [64k-rand-write]
    blocksize=64k
    readwrite=randwrite
    [64k-rand-read]
    blocksize=64k
    readwrite=randread
    [64k-mix-rand-50-50]
    blocksize=64k
    readwrite=randrw
    rwmixread=50
    [64k-mix-rand-80-20]
    blocksize=64k
    readwrite=randrw
    rwmixread=80
    [64k-mix-rand-20-80]
    blocksize=64k
    readwrite=randrw
    rwmixread=20
    ##----Begin 256k tests-------
    [256k-write]
    blocksize=256k
    readwrite=write
    [256k-read]
    blocksize=256k
    readwrite=read
    [256k-rand-write]
    blocksize=256k
    readwrite=randwrite
    [256k-rand-read]
    blocksize=256k
    readwrite=randread
    [256k-mix-rand-50-50]
    blocksize=256k
    readwrite=randrw
    rwmixread=50
    [256k-mix-rand-80-20]
    blocksize=256k
    readwrite=randrw
    rwmixread=80
    [256k-mix-rand-20-80]
    blocksize=256k
    readwrite=randrw
    rwmixread=20
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: px-bench-runner
  namespace: px-bench
data:
  runner.sh: |-
    #!/usr/bin/env sh
    set -eu
    : "${FIO_CONFIG:=/fiocfg/fiojobs.fio}"
    : "${RESULTS_DIR:=/results}"
    : "${RUN_TAG:=}"
    : "${DATA_FILE:=/data/fio.dat}"
    : "${HOURS:=1}"
    : "${DURATION_SECONDS:=}"
    : "${RUNTIME_PER_JOB:=}"
    : "${SIZE:=1GiB}"
    : "${SC_NAME:=unknown}"
    : "${MODE:=single}"
    : "${CACHE_DROP:=true}"
    : "${KEEP_ALIVE:=false}"
    : "${EXTRA_FIO_ARGS:=}"
    : "${JOBS:=}"
    : "${JOB_MODE:=}"
    : "${JOB_FILTER:=}"
    : "${JOB_EXCLUDE:=}"
    : "${ITERATION_SLEEP_SECS:=0}"
    : "${PERCENTILES:=50:95:99}"
    : "${RUNTIME_PRE_JOB:=}"

    # Sanitize numeric inputs to avoid arithmetic errors
    sanitize_integer() {
      case "$1" in
        ''|*[!0-9]*) echo "$2" ;;
        *) echo "$1" ;;
      esac
    }
    HOURS=$(sanitize_integer "${HOURS}" "1")
    ITERATION_SLEEP_SECS=$(sanitize_integer "${ITERATION_SLEEP_SECS}" "0")
    RAMP_TIME=$(sanitize_integer "${RAMP_TIME:-0}" "0")
    case "${DURATION_SECONDS:-}" in
      ''|*[!0-9]*) DURATION_SECONDS="" ;;
    esac
    case "${RUNTIME_PER_JOB:-}" in
      ''|*[!0-9]*) RUNTIME_PER_JOB="" ;;
    esac
    case "${RUNTIME_PRE_JOB:-}" in
      ''|*[!0-9]*) RUNTIME_PRE_JOB="" ;;
    esac
    # Prefer RUNTIME_PRE_JOB if provided
    if [ -n "${RUNTIME_PRE_JOB}" ]; then
      RUNTIME_PER_JOB="${RUNTIME_PRE_JOB}"
    fi

    start_ts=$(date -u +%Y%m%dT%H%M%SZ)
    node_name=$(cat /etc/hostname || true)
    base_dir="${RESULTS_DIR}/${SC_NAME}"
    if [ -n "${RUN_TAG:-}" ]; then
      base_dir="${base_dir}/${RUN_TAG}"
    fi
    base_node_dir="${base_dir}/${node_name}"
    mkdir -p "${base_node_dir}"

    if [ -n "${DURATION_SECONDS}" ]; then
      duration_seconds=${DURATION_SECONDS}
    else
      duration_seconds=$(( ${HOURS} * 3600 ))
    fi
    end_epoch=$(( $(date +%s) + duration_seconds ))

    # Prepare fio args
    fio_args="--output-format=json --filename=${DATA_FILE} --ioengine=libaio --direct=1 --iodepth=128 --end_fsync=1 --size=${SIZE} --percentile_list=${PERCENTILES} ${EXTRA_FIO_ARGS}"
    if [ -n "${RUNTIME_PER_JOB}" ]; then
      fio_args="--runtime=${RUNTIME_PER_JOB} --time_based ${fio_args}"
    fi
    if [ -n "${RAMP_TIME:-}" ]; then
      fio_args="--ramp_time=${RAMP_TIME} ${fio_args}"
    fi
    if [ "${RANDREPEAT:-false}" = "true" ] || [ "${RANDREPEAT:-0}" = "1" ]; then
      fio_args="--randrepeat=1 ${fio_args}"
    fi

    # Determine job execution mode
    run_mode="all_in_one"
    if [ -n "${JOB_MODE}" ]; then
      run_mode="${JOB_MODE}"
    elif [ -n "${JOBS}" ]; then
      run_mode="per_section"
    fi

    # Utility: parse sections from fio config (excluding [global])
    list_sections() {
      awk '/^\[.*\]/{gsub(/\[|\]/,"",$0); if($0!="global") print $0}' "${FIO_CONFIG}"
    }

    # Build job list
    job_list="${JOBS}"
    if [ -z "${job_list}" ] && [ "${run_mode}" = "per_section" ]; then
      sections=$(list_sections)
      if [ -n "${JOB_FILTER}" ]; then
        sections=$(echo "${sections}" | grep -E "${JOB_FILTER}" || true)
      fi
      if [ -n "${JOB_EXCLUDE}" ]; then
        sections=$(echo "${sections}" | grep -Ev "${JOB_EXCLUDE}" || true)
      fi
      if command -v paste >/dev/null 2>&1; then
        job_list=$(echo "${sections}" | paste -sd, -)
      else
        job_list=$(echo "${sections}" | tr '\n' ',' | sed 's/,$//')
      fi
    fi

    i=0
    while [ "$(date +%s)" -lt "${end_epoch}" ]; do
      ts=$(date -u +%Y%m%dT%H%M%SZ)

      if [ "${run_mode}" = "per_section" ]; then
        IFS=','
        for section in ${job_list}; do
          unset IFS
          sec_trim=$(echo "$section" | xargs)
          [ -z "$sec_trim" ] && continue
          out_dir="${base_node_dir}/${sec_trim}"
          mkdir -p "${out_dir}"
          out_json="${out_dir}/${ts}.json"

          if [ "${CACHE_DROP}" = "true" ]; then
            if [ -w /proc/sys/vm/drop_caches ]; then
              sync || true
              echo 3 > /proc/sys/vm/drop_caches || true
            fi
          fi

          echo "[runner] Iter ${i} section ${sec_trim} at ${ts}"
          if [ -n "${CPUSET:-}" ]; then
            taskset -c "${CPUSET}" fio ${fio_args} --section="${sec_trim}" "${FIO_CONFIG}" > "${out_json}" 2> "${out_json}.stderr" || true
          else
            fio ${fio_args} --section="${sec_trim}" "${FIO_CONFIG}" > "${out_json}" 2> "${out_json}.stderr" || true
          fi
          [ "${ITERATION_SLEEP_SECS}" -gt 0 ] && sleep "${ITERATION_SLEEP_SECS}"
        done
      else
        out_dir="${base_node_dir}"
        mkdir -p "${out_dir}"
        out_json="${out_dir}/${ts}.json"

        if [ "${CACHE_DROP}" = "true" ]; then
          if [ -w /proc/sys/vm/drop_caches ]; then
            sync || true
            echo 3 > /proc/sys/vm/drop_caches || true
          fi
        fi

        echo "[runner] Starting fio iteration ${i} at ${ts} (all sections)"
        if [ -n "${CPUSET:-}" ]; then
          taskset -c "${CPUSET}" fio ${fio_args} "${FIO_CONFIG}" > "${out_json}" 2> "${out_json}.stderr" || true
        else
          fio ${fio_args} "${FIO_CONFIG}" > "${out_json}" 2> "${out_json}.stderr" || true
        fi
      fi

      i=$(( i + 1 ))
    done

    echo "[runner] Done. Results in ${RESULTS_DIR}/${SC_NAME}/${node_name}"
    if [ "${KEEP_ALIVE}" = "true" ]; then
      echo "[runner] KEEP_ALIVE=true; sleeping to prevent restart"
      tail -f /dev/null
    fi

apiVersion: batch/v1
kind: Job
metadata:
  annotations:
  generation: 1
  labels:
    app: fio
    job-name: fio-runner
    px-bench: "true"
  name: fio-runner
  namespace: px-bench
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 15
  manualSelector: false
  parallelism: 15
  podReplacementPolicy: TerminatingOrFailed
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fio
        batch.kubernetes.io/job-name: fio-runner
        job-name: fio-runner
        px-bench: "true"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: px-bench
                operator: In
                values:
                - "true"
      containers:
      - command:
        - /bin/sh
        - -lc
        - /runner/runner.sh
        env:
        - name: HOURS
          value: "1"
        - name: RUNTIME_PER_JOB
        - name: SIZE
          value: 1GiB
        - name: SC_NAME
          value: repl1-fastpath
        - name: MODE
          value: repl1-fastpath
        - name: RESULTS_DIR
          value: /results
        - name: KEEP_ALIVE
          value: "false"
        - name: JOB_MODE
          value: per_section
        - name: JOB_FILTER
          value: (read|write)$
        - name: JOB_EXCLUDE
          value: rand|mix
        - name: RUNTIME_PRE_JOB
        - name: DURATION_SECONDS
          value: "600"
        - name: RUN_TAG
          value: parallel-15-sequential-20250926T073449Z
        - name: RANDREPEAT
          value: "false"
        - name: ITERATION_SLEEP_SECS
          value: "0"
        - name: RAMP_TIME
          value: "0"
        image: quay.io/a13x22/alpine-fio
        imagePullPolicy: IfNotPresent
        name: fio
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /results
          name: results
        - mountPath: /fiocfg
          name: fiocfg
        - mountPath: /runner
          name: runner
        - mountPath: /data
          name: test-volume
      dnsPolicy: ClusterFirst
      nodeSelector:
        px-bench: "true"
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: px-bench
      serviceAccountName: px-bench
      terminationGracePeriodSeconds: 30
      volumes:
      - name: results
        persistentVolumeClaim:
          claimName: px-bench-results
      - configMap:
          defaultMode: 420
          name: fiocfg
        name: fiocfg
      - configMap:
          defaultMode: 493
          name: px-bench-runner
        name: runner
      - ephemeral:
          volumeClaimTemplate:
            metadata:
              creationTimestamp: null
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi
              storageClassName: repl1-fastpath
              volumeMode: Filesystem
        name: test-volume

